export enum TypeInputForm {
  TEXT = "TEXT",
  TEXT_AREA = "TEXT_AREA",
  LIST_OPTION = "LIST_OPTION",
  AUTO_COMPLETE_LIST_OPTION = "AUTO_COMPLETE_LIST_OPTION",
  CHECK = "CHECK",
  BI_MULTI_RADIO_CHECK = "BI_MULTI_RADIO_CHECK",
  SINGLE_UPLOAD_FILE = "SINGLE_UPLOAD_FILE",
  MULTI_UPLOAD_FILE = "MULTI_UPLOAD_FILE",
  DATE = "DATE",
  NUMBER = "NUMBER",
  EMAIL = "EMAIL",
  PASSWORD = "PASSWORD"
}
