export interface ResponseUserDto {
  document_id?: string,
  type_ide?: string,
  type_user?: string,
  profile_picture?: string,
  name?: string,
  email?: string,
  phone?: string,
  address?: string,
  date_of_birth?: string,
  is_active?: Boolean,
  is_staff?: Boolean,
  municipality_expedition_dni?: string,
  status?: boolean,
  mandate_contract?: string,
}
